export const API_URL = 'https://backend-front-test.dev.echo-company.ru/api';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const SET_TOKEN = 'SET_TOKEN';

export const START_PASSWORD_RECOVERY_REQUEST = 'START_PASSWORD_RECOVERY_REQUEST';
export const START_PASSWORD_RECOVERY_FAIL = 'START_PASSWORD_RECOVERY_FAIL';
export const START_PASSWORD_RECOVERY_SUCCESS = 'START_PASSWORD_RECOVERY_SUCCESS';

export const END_PASSWORD_RECOVERY_REQUEST = 'END_PASSWORD_RECOVERY_REQUEST';
export const END_PASSWORD_RECOVERY_FAIL = 'END_PASSWORD_RECOVERY_FAIL';
export const END_PASSWORD_RECOVERY_SUCCESS = 'END_PASSWORD_RECOVERY_SUCCESS';

export const LOGOUT = 'LOGOUT';